### ISSUE TITLE
Menu should hug left side of screen

### ISSUE THREAD

**Issue by asianmusicguy** [bonzibudd/Fluent-Metro#45] opened 2020-11-11 16:37 UTC
hi @bonzibudd just discoed your theme great job however upon switching from the metro skin i noted that fluent does  not completely hug my screen leaving a slight gap

**Comment by bonzibudd** [comment] 2020-11-11 18:51
This is actually the intended behavior, to give the menu a "floating" effect. However, I will plan on making an option to remove the gap around the outside.

**Comment by asianmusicguy** [comment] 2020-11-11 19:21
@bonzibudd  oh ok! in that case instead of that just shift the slightly to the right so the gap is slightly more equal? because right now the gap to the left is so small it looks mis aligned thats why i made the ticket am i making sense at all i wish i could provide a screenshot

**Comment by bonzibudd** [comment] 2021-01-25 01:41
The next prerelease will include an option for "Classic border." This makes the entire menu attached to the side of the screen and taskbar like other skins. 
![image](https://user-images.githubusercontent.com/61938331/105650644-59c87180-5e82-11eb-8bac-beb6b556a5f2.png)
I am planning to make another layout for a floating menu, but still connected on the sides.

**Comment by bonzibudd** [comment] 2021-01-27 16:41
Hey @asianmusicguy 

It appears that Open-Shell has added an option to customize this in the latest build: https://ci.appveyor.com/project/passionate-coder/open-shell-menu/build/artifacts

After you install it, you can search for "Offset" and find an option called "Horizontal position offset." If you change that to -9, that should achieve what you're looking for.

Let me know if this works as a solution. If so, I will close the issue.

**Comment by bonzibudd** [comment] 2021-03-06 18:29
Addressed #45 in release 1.3.

**Closed by bonzibudd** 2021-03-06 18:29 UTC
Labels: feature/enhancement
